name: Run CI
on:
  #  push:
  #    branches-ignore:
  #      - develop
  #      - release/**
  #    paths-ignore:
  #      - '**/*.md'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node: [18]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: ConorMacBride/install-package@v1
        with:
          apt: xsel
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
