name: Create snapshot release
on:
  push:
    branches:
      - develop

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        node: [18]
    runs-on: ${{matrix.os}}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: ConorMacBride/install-package@v1
        with:
          apt: xsel
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run test
        run: npm test

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - uses: ConorMacBride/install-package@v1
        with:
          apt: xsel
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: Install
        run: npm ci
      - name: Create snapshot release
        run: bash ./.build/pre-release.sh
      - name: Publish snapshot release to npm
        run: npm run publish-next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
